// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCL-fNZlHfJCsYB67J73CFgfjZd9aBeqsE',
    appId: '1:321073592293:web:9ba4e9d67813c6a349a10c',
    messagingSenderId: '321073592293',
    projectId: 'winter-challenge-23',
    authDomain: 'winter-challenge-23.firebaseapp.com',
    storageBucket: 'winter-challenge-23.appspot.com',
    measurementId: 'G-GVYD4WPPKQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-16T-HY4Ho0XxHfDUPS18kEjynfXclGE',
    appId: '1:321073592293:android:c0ccd31e0093159049a10c',
    messagingSenderId: '321073592293',
    projectId: 'winter-challenge-23',
    storageBucket: 'winter-challenge-23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_eZf60r31s5ROq1kqhI-j0sN6qWcilmg',
    appId: '1:321073592293:ios:96addebac1cac2b649a10c',
    messagingSenderId: '321073592293',
    projectId: 'winter-challenge-23',
    storageBucket: 'winter-challenge-23.appspot.com',
    iosBundleId: 'com.example.christmasChallenge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_eZf60r31s5ROq1kqhI-j0sN6qWcilmg',
    appId: '1:321073592293:ios:fcdefc85235cfdbf49a10c',
    messagingSenderId: '321073592293',
    projectId: 'winter-challenge-23',
    storageBucket: 'winter-challenge-23.appspot.com',
    iosBundleId: 'com.example.christmasChallenge.RunnerTests',
  );
}
